[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flowllm"
version = "0.1.1"
description = "build llm flow"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
    "dashscope",
    "elasticsearch",
    "fastapi",
    "fastmcp",
    "httpx",
    "loguru",
    "mcp",
    "numpy",
    "openai",
    "pydantic",
    "PyYAML",
    "Requests",
    "uvicorn",
    "setuptools",
    "akshare",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flowllm*"]
exclude = ["cookbook*"]

[tool.setuptools.package-data]
flowllm = [
    "config/*.yaml", 
    "op/**/*.yaml",
]

[project.scripts]
flowllm = "flowllm.app:main"

