"""Constants"""

FLOWLLM_SERVICE_INFO = "FLOWLLM_SERVICE_INFO"

FLOWLLM_DEFAULT_HOST = "127.0.0.1"

FLOWLLM_DEFAULT_PORT = 2333

# File IO limits and truncation marker.
DEFAULT_MAX_BYTES = 50 * 1024
MAX_FILE_READ_BYTES = 200 * 1024 * 1024
TRUNCATION_NOTICE_MARKER = "<<TRUNCATION_NOTICE>>"

# Oversized images return path & metadata only (no base64).
DEFAULT_MAX_IMAGE_BYTES = 5 * 1024 * 1024
