site_name: FlowLLM
site_url: https://github.com/flowllm-ai/flowllm
site_description: "Memory Management Framework for Agents"
repo_url: https://github.com/flowllm-ai/flowllm
repo_name: flowllm-ai/flowllm
theme:
  name: shadcn
  image: figure/FlowLLM_logo.png
  show_stargazers: true


plugins:
  - search
  - excalidraw

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
