import_config: default
backend: mcp


flow:
  ant_search:
    flow_content: ant_search_op

  ant_investment:
    flow_content: ant_investment_op

op:
  ant_search_op:
    backend: base_mcp_op
    params:
      mcp_name: ant_supply
      tool_name: search

  ant_investment_op:
    backend: base_mcp_op
    params:
      mcp_name: ant_supply
      tool_name: investment_analysis


external_mcp:
  ant_supply:
    type: sse,
    url: "http://11.160.132.45:8010/sse"
