backend: mcp
import_config: default
enabled_flows:
  #  - get_a_stock_infos
  #  - get_a_stock_news
  - ant_search
  - ant_investment
  - tdx_wenda_quotes
  - tdx_market_quotes
  - tavily_search
  - dashscope_search

flow:
  #  get_a_stock_infos:
  #    flow_content: get_ak_a_code_op >> get_ak_a_info_op >> get_ak_a_spot_op >> get_ak_a_money_flow_op >> get_ak_a_financial_info_op >> merge_ak_a_info_op
  #    stream: false
  #    description: "Retrieve the A-share stock codes from the query, and fetch information about these stocks, including company basic information, current stock price and its change percentage, capital inflow and outflow data for the most recent day, and financial information from the latest quarter."
  #    input_schema:
  #      query:
  #        type: string
  #        description: "user question"

  #  get_a_stock_news:
  #    flow_content: get_ak_a_code_op >> get_ak_a_news_op >> merge_ak_a_info_op
  #    stream: false
  #    description: "Retrieve the A-share stock codes from the query, and obtain the latest news information about these stocks."
  #    input_schema:
  #      query:
  #        type: string
  #        description: "user question"

  ant_search:
    flow_content: mcp@ant_supply@search

  ant_investment:
    flow_content: mcp@ant_supply@investment_analysis

  tdx_wenda_quotes:
    flow_content: mcp@tendency_software@tdx_wenda_quotes

  tdx_market_quotes:
    flow_content: mcp@tendency_software@tdx_PBHQInfo_quotes

  tavily_search:
    flow_content: tavily_search_op

  dashscope_search:
    flow_content: dashscope_search_op


external_mcp:
  ant_supply:
    type: sse,
    url: "http://11.160.132.45:8010/sse"
  tendency_software:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/tendency-software/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"