import_config: default

backend: mcp
disabled_flows:
  - llm_flow
  - llm_flow_stream
  - mock_tool_flow
  - mock_async_tool_flow

flow:

  tavily_search:
    flow_content: tavily_search_op

  dashscope_search:
    flow_content: dashscope_search_op

  bailian_web_search:
    flow_content: bailian_web_search_op

  bocha_web_search:
    flow_content: bocha_web_search_op

  brave_web_search:
    flow_content: brave_web_search_op

  bailian_web_parser:
    flow_content: bailian_web_parser_op



  asset_company:
    flow_content: crawl_ths_company_op >> extract_content_op
    description: "通过股票代码获取公司资料信息，例如：详细情况，高管介绍，发行相关，参控股公司。"
    input_schema:
      code:

      query:
        type: string
        description: "user query"
        required: true


op:
  ant_search_op:
    backend: base_mcp_op
    params:
      mcp_name: ant_supply
      tool_name: search

  ant_investment_op:
    backend: base_mcp_op
    params:
      mcp_name: ant_supply
      tool_name: investment_analysis

  tavily_search_op:
    backend: tavily_search_op
    params:
      save_answer: true

  dashscope_search_op:
    backend: dashscope_search_op
    params:
      save_answer: true

  bailian_web_search_op:
    backend: base_mcp_op
    params:
      mcp_name: tongyi_search
      tool_name: bailian_web_search
      save_answer: true
      input_schema_optional:
        - count
      input_schema_deleted:
        - ctx

  bocha_web_search_op:
    backend: base_mcp_op
    params:
      mcp_name: bochaai_search
      tool_name: bocha_web_search
      save_answer: true
      input_schema_optional:
        - freshness
        - count



  extract_entities_code_op:
    backend: extract_entities_code_op
    params:
      save_answer: true

# https://bailian.console.aliyun.com/?tab=mcp#/mcp-market
external_mcp:
  ant_supply:
    type: sse,
    url: "http://11.160.132.45:8010/sse"



  tongyi_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"

  bochaai_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/bochaai_search/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"

  brave_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/Brave_Search/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"

  qtf_mcp:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/qtf_mcp/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"